common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from news import views

app_name = 'common'

urlpatterns = [
    path('', views.news_search, name='search'),
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'),  name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

jeby_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # path('', views.news_search, name='search'),
    path('search/', views.news_search, name='search'),
    path('keyword/', views.KeywordList.as_view(), name='keyword'),
    path('keyword/create/', views.KeywordCreate.as_view(), name='keyword_create'),
    path('keyword/update/<int:pk>/',
        views.KeywordUpdate.as_view(), name='keyword_update'),
    path('keyword/delete/<int:pk>/', views.keyword_delete, name='keyword_delete'),
    path('recipient/', views.RecipientList.as_view(), name='recipient'),
    path('recipient/create/', views.RecipientCreate.as_view(), name='recipient_create'),
    path('recipient/update/<int:pk>/',
        views.RecipientUpdate.as_view(), name='recipient_update'),
    path('recipient/delete/<int:pk>/', views.recipient_delete, name='recipient_delete'),
    path('email/', views.email_setting, name='email_setting'),
    path('email/update/<int:pk>/', views.SettingUpdate.as_view(), name='setting_update'),
    path('site', views.SiteCreateGenericAPIView.as_view(), name='site_create'),
    path('site/<int:pk>',
        views.SiteUpdateGenericAPIView.as_view(), name='site_update'),
    path('share', views.share_news, name='share'),
]

jeby_prj/templates/base.html
{% load static %}

<!doctype html>

<html lang="ko" class="h-100">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1 minimum-scale=1, maximum-scale=1, user-scalable=no">

        <title>
            {% block title %}Jeby{% endblock title %}
        </title>

        <link rel="shortcut icon" href="{% static 'images/swallow_16px.png' %}"/>
        <link rel="icon" sizes="152x152" href="{% static 'images/swallow_152px.png' %}"/>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&family=Noto+Sans+KR:wght@300;400;500&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'bootstrap/bootstrap-5.0.2/css/bootstrap.min.css' %}"/>

        {% block custom_css %}{% endblock custom_css %}
    </head>

    {% block body %}
    {% endblock body %}

    {% block script %}
        <script src="https://kit.fontawesome.com/5b01bdb70e.js" crossorigin="anonymous"></script>
        <script src="{% static 'bootstrap/bootstrap-5.0.2/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'jquery/jquery-3.6.0/jquery-3.6.0.min.js' %}"></script>
    {% endblock script %}
</html>

jeby_prj/templates/base_news.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'news/css/base_news.css' %}"/>
{% endblock custom_css %}

{% block body %}
<body class="d-flex flex-column h-100">
    {% include 'navbar.html' %}

    <div class="container" id="error_msg">
        <div class="row">
            <div class="col">
                {% include "errors.html" %}
            </div>
        </div>
    </div>
    
    <main class="h-100">
        {% block content %}
        {% endblock content %}
    </main>

    {% block footer %}
        {% comment %} {% include 'footer.html' %} {% endcomment %}
    {% endblock footer %}

</body>
{% endblock body %}

{% block script %}
    {{ block.super }}

{% endblock script %}

jeby_prj/templates/errors.html
{% if error_msg %}
    <div class="alert alert-danger" style="padding: 10px 16px">
        {{ error_msg }}
    </div>
{% endif %}

jeby_prj/templates/footer.html
    <footer class="footer mt-auto py-2 bg-light border-top border-1">
        <div class="container text-center">
            <span class="text-muted">@ 2021 engyjoon</span>
        </div>
    </footer>

jeby_prj/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger" style="padding: 10px 16px">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger" style="padding: 10px 16px">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

jeby_prj/templates/navbar.html
 {% load static %}
 
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light border-bottom border-1 mb-0">
        <div class="container">
            <a class="navbar-brand" href="{% url 'news:search' %}">
                <img src="{% static 'images/swallow_152px.png' %}" alt="" height="31" 
                    class="d-inline-block align-text-top">
                <span>Jeby</span>
            </a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'news:search' %}">뉴스검색</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'news:keyword' %}">키워드관리</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'news:recipient' %}">수신자관리</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'news:email_setting' %}">이메일설정</a>
                    </li>
                </ul>
            </div>
            <form class="d-flex">
                {% csrf_token %}
                <button class="navbar-toggler me-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" 
                    aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation"
                    id="toggle-button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a href="{% url 'common:logout' %}" class="btn btn-outline-secondary nav-button me-2" type="button">
                    {% if user.is_authenticated %}
                        logout
                    {% endif %}
                </a>
                {% comment %} 
                <a href="#" class="btn btn-outline-secondary nav-button" type="button">
                    <i class="bi bi-gear"></i>
                </a>
                {% endcomment %}
            </form>
        </div>
        <div class="collapse navbar-toggler p-0 mt-2 w-100 border-bottom-0" id="navbarToggleExternalContent">
            <div class="py-2 px-3">
                <div class="nav-item-mobile"><a href="{% url 'news:search' %}">뉴스검색</a></div>
                <div class="nav-item-mobile"><a href="{% url 'news:keyword' %}">키워드관리</a></div>
                <div class="nav-item-mobile"><a href="{% url 'news:email_setting' %}">이메일설정</a></div>
            </div>
        </div>
    </nav>