common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from news import views

app_name = 'common'

urlpatterns = [
    path('', views.news_search, name='search'),
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'),  name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

jeby_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # path('', views.news_search, name='search'),
    path('search/', views.news_search, name='search'),
    path('keyword/', views.KeywordList.as_view(), name='keyword'),
    path('keyword/create/', views.KeywordCreate.as_view(), name='keyword_create'),
    path('keyword/update/<int:pk>/',
        views.KeywordUpdate.as_view(), name='keyword_update'),
    path('keyword/delete/<int:pk>/', views.keyword_delete, name='keyword_delete'),
    path('recipient/', views.RecipientList.as_view(), name='recipient'),
    path('recipient/create/', views.RecipientCreate.as_view(), name='recipient_create'),
    path('recipient/update/<int:pk>/',
        views.RecipientUpdate.as_view(), name='recipient_update'),
    path('recipient/delete/<int:pk>/', views.recipient_delete, name='recipient_delete'),
    path('email/', views.email_setting, name='email_setting'),
    path('email/update/<int:pk>/', views.SettingUpdate.as_view(), name='setting_update'),
    path('site', views.SiteCreateGenericAPIView.as_view(), name='site_create'),
    path('site/<int:pk>',
        views.SiteUpdateGenericAPIView.as_view(), name='site_update'),
    path('share', views.share_news, name='share'),
]

common/views.py
from django.shortcuts import render

# Create your views here.

jeby_prj/templates/common/login.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'common/css/login.css' %}"/>
{% endblock custom_css %}

{% block body %}
    <body class="text-center">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% include "form_errors.html" %}
                </div>
            </div>
            <div class="row">
                <main class="form-signin">
                    <form method="post" action="{% url 'common:login' %}">
                        {% csrf_token %}
                        <img class="mb-2" src="{% static 'images/swallow_152px.png' %}" alt="" width="120" height="120">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="username" placeholder="ID"
                                name="username" value="{{ form.username.value|default_if_none:'' }}">
                            <label for="username">ID</label>
                        </div>
                        <div class="form-floating">
                            <input type="password" class="form-control" id="password" placeholder="Password"
                                name="password" value="{{ form.password.value|default_if_none:'' }}">
                            <label for="password">Password</label>
                        </div>
                        <div class="checkbox mb-3">
                            <label>
                                <input type="checkbox" value="remember-me"> Remember me
                            </label>
                        </div>
                        <button class="w-100 btn btn-lg btn-primary" type="submit">Log in</button>
                        <p class="mt-5 mb-3 text-muted"></p>
                    </form>
                </main>
            </div>
        </div>
    </body>
{% endblock body %}