jeby_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # path('', views.news_search, name='search'),
    path('search/', views.news_search, name='search'),
    path('keyword/', views.KeywordList.as_view(), name='keyword'),
    path('keyword/create/', views.KeywordCreate.as_view(), name='keyword_create'),
    path('keyword/update/<int:pk>/',
        views.KeywordUpdate.as_view(), name='keyword_update'),
    path('keyword/delete/<int:pk>/', views.keyword_delete, name='keyword_delete'),
    path('recipient/', views.RecipientList.as_view(), name='recipient'),
    path('recipient/create/', views.RecipientCreate.as_view(), name='recipient_create'),
    path('recipient/update/<int:pk>/',
        views.RecipientUpdate.as_view(), name='recipient_update'),
    path('recipient/delete/<int:pk>/', views.recipient_delete, name='recipient_delete'),
    path('email/', views.email_setting, name='email_setting'),
    path('email/update/<int:pk>/', views.SettingUpdate.as_view(), name='setting_update'),
    path('site', views.SiteCreateGenericAPIView.as_view(), name='site_create'),
    path('site/<int:pk>',
        views.SiteUpdateGenericAPIView.as_view(), name='site_update'),
    path('share', views.share_news, name='share'),
]

news/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User
from django.db.models import constraints
from django.db.models.fields import CharField
from django.db.models.fields.related import ManyToManyField


class Keyword(models.Model):
    title = models.CharField(max_length=50, verbose_name='관리명', unique=False)
    content = models.CharField(max_length=100, verbose_name='키워드')
    mailing = models.BooleanField(default=False, verbose_name='메일발송')
    shared = models.BooleanField(default=False, verbose_name='공유')
    order = models.IntegerField(
        validators=[MinValueValidator(1)],
        unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order']
        constraints = [
            models.UniqueConstraint(
                fields=['title', 'author'], name='unique title for author')
        ]


class Recipient(models.Model):
    name = models.CharField(max_length=50, verbose_name='이름')
    email = models.EmailField(verbose_name='이메일')
    note = models.CharField(max_length=50, verbose_name='비고', null=False, blank=True)
    order = models.IntegerField(
        validators=[MinValueValidator(1)],
        unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.email + '(' + self.name + ')'
    
    class Meta:
        ordering = ['order']
        constraints = [
            models.UniqueConstraint(
                fields=['email', 'author'], name='unique email for author')
        ]


class Setting(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    email_send_time = CharField(
        max_length=100, verbose_name='메일발송시간', null=True, blank=True)
    work_hour = CharField(
        max_length=50, verbose_name='업무시간', null=True, blank=True)
    email_recipients = ManyToManyField(Recipient, blank=True)

    def __str__(self):
        return self.author.username


class Site(models.Model):
    address = models.CharField(max_length=100, verbose_name='Address')
    description = models.CharField(max_length=100, verbose_name='Description')

    def __str__(self):
        return self.description

news/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.core.exceptions import PermissionDenied

from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication, BasicAuthentication

from .models import Keyword, Recipient, Setting, Site
from .serializers import SiteSerializer
from . import naverapi, utils


@login_required(login_url="common:login")
def index(request):
    """
    뉴스 검색 첫 페이지를 반환한다.
    """
    keywords = Keyword.objects.all()

    return render(
        request,
        "news/index.html",
        {
            "keywords": keywords,
        },
    )


@login_required(login_url="common:login")
def news_search(request):
    """
    키워드 검색 페이지에서 사용한다.
    키워드로 뉴스를 검색한다.
    """
    form = {}
    error_msg = None
    template_name = "news/read.html"

    # 사용자가 등록한 키워드를 조회하여 반환한다.
    current_user = request.user
    keywords = Keyword.objects.filter(author=current_user)

    # 수신자를 조회한다.
    email_users = Recipient.objects.filter(author=current_user)

    news = None

    if request.method == "GET":
        return render(
            request,
            template_name,
            {
                "keywords": keywords,
                "email_users": email_users,
            },
        )
    elif request.method == "POST":
        keyword = request.POST.get("keyword").strip()

        # 키워드를 입력하지 않을 경우 관련 메지지를 반환한다.
        if keyword is None or keyword == "":
            error_msg = "키워드를 입력해 주세요."
        # 키워드를 입력했을 경우 최근 24간 뉴스 리스트를 반환한다.
        else:
            if current_user.username == "imsi":
                news = naverapi.get_news_from_january(keyword)
            else:
                news = naverapi.get_news_by_hour(keyword, start_hour=24)
            form["keyword"] = keyword

        return render(
            request,
            template_name,
            {
                "news": news,
                "form": form,
                "error_msg": error_msg,
                "keywords": keywords,
                "email_users": email_users,
            },
        )


class KeywordList(LoginRequiredMixin, ListView):
    """
    키워드 관리 페이지에서 사용한다.
    키워드 리스트를 반환한다.
    """

    login_url = "common:login"
    model = Keyword

    def get_queryset(self):
        current_user = self.request.user
        keyword_list = Keyword.objects.filter(author=current_user)

        return keyword_list


class KeywordCreate(LoginRequiredMixin, CreateView):
    """
    키워드 관리 페이지에서 사용한다.
    키워드를 생성한다.
    """

    login_url = "common:login"
    success_url = reverse_lazy("news:keyword")
    model = Keyword
    fields = ["title", "content", "mailing", "shared"]

    def form_valid(self, form):
        keyword_last = Keyword.objects.last()
        if keyword_last:
            form.instance.order = keyword_last.pk + 1
        else:
            form.instance.order = 1

        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            response = super(KeywordCreate, self).form_valid(form)

            return response
        else:
            return redirect("news:keyword")


class KeywordUpdate(LoginRequiredMixin, UpdateView):
    """
    키워드 관리 페이지에서 사용한다.
    키워드를 수정한다.
    """

    login_url = "common:login"
    success_url = reverse_lazy("news:keyword")
    model = Keyword
    fields = ["title", "content", "mailing", "shared"]

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(KeywordUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


@login_required(login_url="common:login")
def keyword_delete(request, pk):
    """
    키워드 관리 페이지에서 사용한다.
    키워드를 삭제한다.
    """
    keyword = get_object_or_404(Keyword, pk=pk)
    if request.user == keyword.author:
        keyword.delete()
        return redirect("news:keyword")
    else:
        raise PermissionDenied


class RecipientList(LoginRequiredMixin, ListView):
    """
    수신자 관리 페이지에서 사용한다.
    수신자 리스트를 반환한다.
    """

    login_url = "common:login"
    model = Recipient

    def get_queryset(self):
        current_user = self.request.user
        recipient_list = Recipient.objects.filter(author=current_user)

        return recipient_list


class RecipientCreate(LoginRequiredMixin, CreateView):
    """
    수신자 관리 페이지에서 사용한다.
    수신자를 생성한다.
    """

    login_url = "common:login"
    success_url = reverse_lazy("news:recipient")
    model = Recipient
    fields = ["name", "email", "note"]

    def form_valid(self, form):
        recipient_last = Recipient.objects.last()
        if recipient_last:
            form.instance.order = recipient_last.order + 1
        else:
            form.instance.order = 1

        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            response = super(RecipientCreate, self).form_valid(form)

            return response
        else:
            return redirect("news:recipient")


class RecipientUpdate(LoginRequiredMixin, UpdateView):
    """
    수신자 관리 페이지에서 사용한다.
    수신자를 수정한다.
    """

    login_url = "common:login"
    success_url = reverse_lazy("news:recipient")
    model = Recipient
    fields = ["name", "email", "note"]

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(RecipientUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


@login_required(login_url="common:login")
def recipient_delete(request, pk):
    """
    수신자 관리 페이지에서 사용한다.
    수신자를 삭제한다.
    """
    recipient = get_object_or_404(Recipient, pk=pk)
    if request.user == recipient.author:
        recipient.delete()
        return redirect("news:recipient")
    else:
        raise PermissionDenied


class SiteCreateGenericAPIView(generics.CreateAPIView):
    """
    뉴스 검색 페이지에서 언론사를 생성하면 호출된다.
    """

    serializer_class = SiteSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]


class SiteUpdateGenericAPIView(generics.UpdateAPIView):
    """
    뉴스 검색 페이지에서 언론사를 수정하면 호출된다.
    """

    queryset = Site.objects.all()
    serializer_class = SiteSerializer
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]


@login_required(login_url="common:login")
@api_view(["GET", "POST"])
def share_news(request):
    """
    뉴스 검색 후 선택한 뉴스를 공유하면
    지정된 수신자에게 선택한 뉴스를 이메일로 발송한다.
    """
    if request.method == "POST":
        data = request.data
        utils.send_email_by_share(data)

        return JsonResponse({"result": "success"})


@login_required(login_url="common:login")
def email_setting(request):
    """
    이메일설정 페이지에서 사용한다.
    이메일 설정 정보를 반환한다.
    """
    current_user = request.user

    # setting model과 선택한 이메일 수신자를 조회한다.
    try:
        setting = Setting.objects.get(author=request.user.id)
    except Setting.DoesNotExist:
        setting = Setting()
        setting.author = current_user
        setting.save()

    # 선택한 이메일 수신자를 조회한다.
    setting_recipients = setting.email_recipients.all()

    # 선택 가능한 이메일 수신자를 조회한다.
    try:
        recipients = Recipient.objects.filter(author=current_user)
    except Recipient.DoesNotExist:
        recipients = None

    return render(
        request,
        "news/email_setting.html",
        {
            "setting": setting,
            "setting_recipients": setting_recipients,
            "recipients": recipients,
        },
    )


class SettingUpdate(LoginRequiredMixin, UpdateView):
    """
    이메일 설정 페이지에서 사용한다.
    발송시간, 업무시간, 수신자를 수정한다.
    """

    login_url = "common:login"
    success_url = reverse_lazy("news:email_setting")
    model = Setting
    template_name = "news/email_setting.html"
    fields = ["email_send_time", "work_hour", "email_recipients"]

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(SettingUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(SettingUpdate, self).form_valid(form)
        self.object.email_recipients.clear()

        email_recipients_str = self.request.POST.get("email_recipients_str")
        if email_recipients_str:
            _list = email_recipients_str.split(";")
            for pk in _list:
                recipient = Recipient.objects.get(pk=pk)
                self.object.email_recipients.add(recipient)

        return response

jeby_prj/templates/news/keyword_form.html
{% extends 'base_news.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block custom_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'news/css/keyword_form.css' %}"/>
{% endblock custom_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <table>
                    {{ form | crispy }}
                </table>
                <div class="float-end">
                    <a href="{% url 'news:keyword' %}" type="button" class="btn btn-outline-secondary" id="btn-list">목록</a>
                    <button type="sumit" class="btn btn-primary">저장</button>
                    {% if keyword %}
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" 
                        data-bs-target="#deleteKeywordModal">삭제</button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteKeywordModal" tabindex="-1" aria-labelledby="deleteKeywordModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">삭제하기</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        정말 삭제하시겠습니까?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        {% if keyword %}
            <a href="{% url 'news:keyword_delete' keyword.id %}" type="button" class="btn btn-danger">Delete</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>

</div>
{% endblock content %}

{% block script %}
    {{ block.super }}
    <script src="{% static 'news/js/keyword_form.js' %}"></script>
{% endblock script %}

jeby_prj/templates/news/keyword_list.html
{% extends 'base_news.html' %}

{% load static %}

{% block custom_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'news/css/keyword_list.css' %}"/>
{% endblock custom_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="d-flex flex-row-reverse mb-2">
                <a href="{% url 'news:keyword_create' %}" type="button" class="btn btn-primary">등록</a>
            </div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" style="width:20%;">관리명</th>
                            <th scope="col">키워드</th>
                            <th scope="col" style="width:10%;">메일</th>
                            <th scope="col" style="width:10%;">공유</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for keyword in keyword_list %}
                        <tr>
                            <td scope="row"><a href="{% url 'news:keyword_update' keyword.id %}">{{ keyword.title }}</a></td>
                            <td><a href="{% url 'news:keyword_update' keyword.id %}">{{ keyword.content }}</a></td>
                            <td><a href="{% url 'news:keyword_update' keyword.id %}">{{ keyword.mailing }}</a></td>
                            <td><a href="{% url 'news:keyword_update' keyword.id %}">{{ keyword.shared }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
    {{ block.super }}
    <script src="{% static 'news/js/keyword_list.js' %}"></script>
{% endblock script %}

jeby_prj/templates/news/read.html
{% extends 'base_news.html' %}

{% load static %}

{% block custom_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'news/css/news_read.css' %}"/>
{% endblock custom_css %}

{% block content %}
<div class="container" id="search-box">
    <div class="d-flex flex-column">
        <form action="{% url 'news:search' %}" method="post" id="frm-search">
            {% csrf_token %}

            {% if not form %}
            <div class="row mb-1">
                <div class="col text-center">
                    <p class="h4" id="search-title">뉴스 검색 키워드를 입력하세요.</p>
                </div>
            </div>
            {% endif %}

            <div class="row" style="padding-bottom:16px;">
                <div class="col">
                    <div class="card border-secondary shadow-sm">
                        <div class="card-body" id="keyword-box">
                            <div class="d-flex flex-row">
                                <button type="button" class="btn btn-secondary" id="btn-keyword-group"
                                    data-bs-toggle="modal" data-bs-target="#keywordListModal">키워드</button>
                                <div class="flex-grow-1">
                                    <input type="text" class="form-control" name="keyword" id="input-keyword" 
                                    value="{{ form.keyword }}" autocomplete=off>
                                </div>
                                <div class="me-2">
                                    <a href="#"><span id="search-img"><i class="fas fa-search"></i></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        {% if form %}
        <div class="row mb-3" id="selectedNews">
            <div class="col">
                <div class="card border-primary">
                    <div class="card-header d-flex">
                        <div>선택뉴스 (<span id="selectedCount"></span>건)</div>
                        <div class="ms-auto">
                            <a href="#" data-bs-toggle="modal" data-bs-target="#shareNewsModal"><i class="bi bi-share-fill"></i> 공유하기</a>
                        </div>
                    </div>
                    <div class="card-body py-2" id="selectedNewsBody">
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        검색뉴스 ({{ news|length }}건)
                    </div>
                    <div class="card-body py-2">
                        {% if news %}
                            {% for new in news %}
                                <div class="news-item fs-6" id="news-{{ forloop.counter }}">
                                    <span class="check-sitename me-2">
                                        <i class="bi bi-square"></i>
                                    </span>
                                    <span class="box-sitename me-2">
                                        {% if new.sitename == 'unknown' %}
                                            <a href="#" style="font-weight:100; color:#D9C3CE"
                                                data-bs-toggle="modal" data-bs-target="#siteEditModal"
                                                data-siteuri="{{ new.siteuri }}" data-sitename=""
                                                data-action-url="{% url 'news:site_create' %}" data-action-type="create"
                                                data-sitename="">
                                                등록하기</a>
                                        {% else %}
                                            <a href="#"
                                                data-bs-toggle="modal" data-bs-target="#siteEditModal"
                                                data-siteuri="{{ new.siteuri }}" data-sitename="{{ new.sitename }}"
                                                data-action-url="{% url 'news:site_update' new.siteid %}" data-action-type="update"
                                                data-sitename="{{ new.sitename }}">
                                                {{ new.sitename }}</a>
                                        {% endif %}
                                    </span>
                                    <a href="{{ new.originallink }}" target="_blank">
                                        <span class="news-title" style="font-weight:400;">
                                            {{ new.title|safe|truncatechars:50 }}
                                        </span>
                                    </a>
                                    <span class="badge bg-light text-dark">{{ new.pubDate|date:"Y/m/d H:i:s" }}</span>
                                </div>
                            {% endfor %}
                        {% else %}
                            검색된 뉴스가 없습니다.
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

    </div>
</div>

<div class="modal fade" id="keywordListModal" tabindex="-1" aria-labelledby="keywordListModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="keywordListModalLabel">키워드 선택하기</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" style="width:30%;">관리명</th>
                            <th scope="col">키워드</th>
                            <th scope="col" style="width:20%;">액션</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for keyword in keywords %}
                        <tr>
                            <td>{{ keyword.title }}</td>
                            <td>{{ keyword.content }}</td>
                            <td>
                                <button type="button" class="btn btn-sm btn-primary btn-select-keyword"
                                    data-keyword="{{ keyword.content }}">선택</button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="siteEditModal" tabindex="-1" aria-labelledby="siteEditModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <form id="frmSiteEditModeal" action="">
                <div class="modal-header">
                    <h5 class="modal-title" id="siteEditModalLabel">언론사 수정하기</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="modal-siteuri" class="form-label">Address</label>
                        <input type="text" class="form-control" id="modal-siteuri" disabled readonly>
                    </div>
                    <div class="mb-2">
                        <label for="modal-sitedesc" class="form-label">Description</label>
                        <input type="text" class="form-control" id="modal-sitedesc" autocomplete=off>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnSaveSiteEditModal">Save</button>
                </div>  
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="shareNewsModal" tabindex="-1" aria-labelledby="shareNewsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <form id="frmShareNewsModal" action="{% url 'news:share' %}">
                <div class="modal-header">
                    <h5 class="modal-title" id="shareNewsModalLabel">뉴스 공유하기</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="alert" style="padding: 8px 14px;" id="shareNewsModalMessage"></div>
                    <div class="mb-3">
                        <label for="selectRecipient" class="form-label">수신자</label>
                        <select class="form-select" id="selectRecipient">
                            <option value="" selected>선택하세요.</option>
                            {% for user in email_users %}
                                <option value="{{ user.email }}">{{ user.email }} ({{ user.name }})</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="message-title" class="col-form-label">제목</label>
                        <input type="text" class="form-control" id="message-title" autocomplete=off>
                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">메시지</label>
                        <textarea class="form-control" id="message-text" rows="5"></textarea>
                    </div>
                </div>
                <div class="modal-footer d-flex">
                    <div class="me-auto" id="spinnerEmail">
                        <span class="spinner-grow spinner-grow-sm text-secondary" role="status"></span>
                        Sending mail...
                    </div>
                    <div>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="btnShareNewsModal">Share</button>
                    </div>
                </div>  
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
{% comment %} <footer class="footer mt-auto py-2 bg-light border-top border-1">
    <div class="container text-center">
        <span class="text-muted">@ 2021 engyjoon</span>
    </div>
</footer> {% endcomment %}
{% endblock footer %}

{% block script %}
    {{ block.super }}
    <script src="{% static 'news/js/news_read.js' %}"></script>
{% endblock script %}

jeby_prj/templates/news/recipient_form.html
{% extends 'base_news.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block custom_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'news/css/recipient_form.css' %}"/>
{% endblock custom_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <table>
                    {{ form | crispy }}
                </table>
                <div class="float-end">
                    <a href="{% url 'news:recipient' %}" type="button" class="btn btn-outline-secondary" id="btn-list">목록</a>
                    <button type="sumit" class="btn btn-primary">저장</button>
                    {% if recipient %}
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" 
                        data-bs-target="#deleteRecipientModal">삭제</button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteRecipientModal" tabindex="-1" aria-labelledby="deleteRecipientModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">삭제하기</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        정말 삭제하시겠습니까?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        {% if recipient %}
            <a href="{% url 'news:recipient_delete' recipient.id %}" type="button" class="btn btn-danger">Delete</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>

</div>
{% endblock content %}

{% block script %}
    {{ block.super }}
    <script src="{% static 'news/js/recipient_form.js' %}"></script>
{% endblock script %}

jeby_prj/templates/news/recipient_list.html
{% extends 'base_news.html' %}

{% load static %}

{% block custom_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'news/css/recipient_list.css' %}"/>
{% endblock custom_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="d-flex flex-row-reverse mb-2">
                <a href="{% url 'news:recipient_create' %}" type="button" class="btn btn-primary">등록</a>
            </div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" style="width:20%;">이름</th>
                            <th scope="col" style="width:30%;">이메일</th>
                            <th scope="col">비고</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for recipient in recipient_list %}
                        <tr>
                            <td scope="row"><a href="{% url 'news:recipient_update' recipient.id %}">{{ recipient.name }}</a></td>
                            <td><a href="{% url 'news:recipient_update' recipient.id %}">{{ recipient.email }}</a></td>
                            <td><a href="{% url 'news:recipient_update' recipient.id %}">{{ recipient.note }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
    {{ block.super }}
    <script src="{% static 'news/js/recipient_list.js' %}"></script>
{% endblock script %}